var Bandnames = new Array(

	'Polish Bulldog and The Sulfuric Turds ',
	'More Funky Guitars ',
	'Mr Feely Good ',
	'Captain Salami and The Sausage Seven ',
	'Fisher McNeely and The Dolphin Floggers ',
	'Adam C and The C-Notes ',
	'My First Music Lesson ',
	'Funky Cold Medina and The Dripping Lesbians ',
	'Rabid Burger and the Top Notch Smokers ',
	'Robert F. Killmore and the Silver Surfers ',
	'Funky Tuna and The Greasy Sardines ',
	'Sideshow Debauchery and the Fist of Blazing Steel ',
	'Nine Below Zero ',
	'Sicle Sell Sombrero ',
	'Tentacle Amphibian ',
	'The Funknuggets ',
	'Testicular Gonzo ',
	'Time Share and the Metamorphous Trio ',
	'Metamophine Man ',
	'Halfback Rhombus and the Distant Grandson ',
	'First Day of School ',
	'Teddy Smooth and the First Amendment Gangsters ',
	'Rufus Quiggleby and the 5-Blunt 4 ',
	'Bill Gates and The Microsoft Killaz ',
	'Los Gatos De Infierno ',
	'Los Perros De Canguelo ',
	'Los Canguelistas ',
	'Los Dumass ',
	'The Funky Penguins ',
	'The Real Jeruselem 5 ',
	'Tension Between Lovers ',
	'The Jersey Turnpike ',
	'Rockers Beyond Borders ',
	'Funk Over Vegas ',
	'Angel Archeologist ',
	'Ray Gunn and the Technical Phantom ',
	'Laser Larry and The Retinal Scan ',
	'Invisible Subsidiary of Mrs Thompson ',
	'Mr. Thompson\'s Nuts ',
	'Fiberglass Fingers and the Dizzy Dino Squad ',
	'Walnuts For Freedom ',
	'Chastidy Cummings and the First Timers ',
	'Potatoe Jamaica and the Eggplant Posse ',
	'Fishy McSquid and the Tartar Sauce ',
	'Fertile Fergusson and Last Week\'s Spaghetti ',
	'Jars of Semen ',
	'Incandescent Glow and the Hip Poppies ',
	'Opium Joe and the Poppy Pusher ',
	'The Scrumtrulescence ',
	'Tiger Roughman and the Self Proclaimed Messiahs ',
	'telephonic word associations ',
	'Mister E. and the Hypnotics ',
	'Professor Green and the Keyboard Pharmacists ',
	'Massachusetts Mayor and the Identicle Tenticles ',
	'Verbal Unification ',
	'Christopher Columbus and the Mississippi River Scandal ',
	'Cold Steel and the Dirty Dishes ',
	'Flex Armaggeddon and his Hungry Sister ',
	'Mr Clean and the Putrid Waste Clean up Crew ',
	'Hologram Frontman and the Busy Beavers ',
	'Black Charles and the Playa Hatas ',
	'One-Eyed Wonder Weasel and His Two Brass Balls ',
	'Holiday Handgranade and the Huckleberry 4 ',
	'Possible Predilection ',
	'Overboard Octopus ',
	'Porcupine Carl and the Sizzling Sofas ',
	'Solo Phone booth and the Package Adjusters ',
	'Ten Blunts To The Door ',
	'Cross Continental Serial Cucumbers ',
	'Shuffle Board Playoffs ',
	'Super Unleaded Alligator ',
	'Breakfast With Boris ',
	'In Bed With The Russians ',
	'Turbo Diesel Ocelot ',
	'Ivan and The Red Warriors ',
	'Diablos Blancos ',
	'Diablos De Cabras ',
	'Lexus Chainstore Massochists ',
	'What\'s A Cabras ',
	'Rhymez 4 Jesus ',
	'King Cobra and the Tiny Mammal Carcasses ',
	'Six Ways To Die On An Elevator ',
	'Fourth Floor Janitors ',
	'Electric Emu ',
	'Two Terrible Mothers ',
	'P & S N V ',
	'The Typos ',
	'Scandinavian Fantasy ',
	'Army Mishaps and the Expert Witness ',
	'Norwegian Wunderkind ',
	'The Ifs, Ands, or Buts ',
	'Eddie Alto and the Aquarium Fish ',
	'Mission and the Possibilities ',
	'T minus Two ',
	'Adam C Fresh and the Stupid Band Names ',
	'Alter Ego and The Journey To The Sun ',
	'Altair Cunnilingus and the Ballistic Mouth ',
	'Maximum Heat and the Alternative Endings ',
	'Hitchhikers Guide To Your Underpants ',
	'First Degree Burn and the Nasty Scabs ',
	'Pimp Dictionary ',
	'Infinite Improbability Function and The Flux Capacitors ',
	'Superstar Keg Standers ',
	'Islam Mohammed and the Suicide Bombers ',
	'Blood Suckin Crawfish ',
	'Psycho Elevator React Juice ',
	'Disney Dollars For Scholars ',
	'Steve Hydropower and the River Flow Five ',
	'Necktie Nonsense and the Defribulators ',
	'Guatamalen Henchmen ',
	'Thats My Cordless Drill! ',
	'Wildebeast Wilde and the Undercover Brothers ',
	'Steve Irwin and the Alligator Trio ',
	'Max Power and the Heirloom doom band ',
	'Centipede Slug and the Earthworm Trio ',
	'Red Eyed Monkey Frogs ',
	'Silver Tongued Paradise ',
	'Ganglion and the Stem Cell Squad ',
	'Random Animal and the Googly-Eyed Monsters ',
	'Christians vs. Beelzebubs\' Funk Force ',
	'Funk Force Five ',
	'Hip Hop Squatters ',
	'Old School Detention Center ',
	'Dirt Bag Mulligan and the Obsessive Compulsions ',
	'Aardvark Malone and The Right Hand of The Father ',
	'Five Times Earths Gravity ',
	'Jupiter Shoes and the Chinese Three ',
	'Buddha Bob and the Next Level Schananigans ',
	'Elmo and the 2 hitter Quitters ',
	'Spasm of the Plasm ',
	'Faggot Milk ',
	'Spasmilk ',
	'Milk Plasm ',
	'Dead Milk Men ',
	'5 Seconds Til Doom ',
	'2% Real ',
	'Jumbo Foul-Mouth ',
	'Caution Tape Crew ',
	'The Answer Is Vitamin ',
	'Instant Almanac ',
	'Alien France ',
	'RAPE ZOO ',
	'Marshmallow Nixon ',
	'The Sweet Saline Drips ',
	'Launch Pad McQuack ',
	'The Robot Street Blues Quartet ',
	'International Hooligans ',
	'Christmas in Jamaica ',
	'Whiplash Laser ',
	'Beatbox Banditos ',
	'Amen Mercury ',
	'One Leg At a Time ',
	'African Sunrise ',
	'Talk Like A Planet ',
	'Mob Boss Mayhem ',
	'Funk In The Trunk ',
	'Cemetary Nuckas ',
	'Hard-Boiled Milk ',
	'Lusty Ruck Nuckas ',
	'Robust Teargas ',
	'Easygoing Teens ',
	'Happy Days With A Lot Of Vegetables ',
	'Tornado Rhombus ',
	'Green Top Farmers ',
	'Monopoly Copy squadron ',
	'Spontaneus Regiment ',
	'The Tempermental Zealots ',
	'Tyrannosaurus Best ',
	'Momentous Frost Force ',
	'Paddy Wagon Radio ',
	'Prostitution Police ',
	'Detox Platoon ',
	'Highfalutin Fellows ',
	'Rococo Columbo ',
	'Barbar Is Dead ',
	'Bottles Of James ',
	'Kooky Mental Firemen ',
	'Dookie Dental ',
	'Hankerin for a Donut ',
	'Hyper Pickle ',
	'Nickel Science ',
	'The Eastern European Waffle Festival ',
	'Rascal Ruffian ',
	'Hooligan Holigram ',
	'Rouge Ogre ',
	'The Dickens ',
	'The Virgin Organisms ',
	'The Better Halves ',
	'Bosom Buddies ',
	'Funky Riddle ',
	'Sticker on the Spinx ',
	'Mammal Dick ',
	'Who-Done-It ',
	'Mystery Poser ',
	'The Cliff-Hangers ',
	'You\'re Sister Is Pregnant ',
	'Rumple Pumpers ',
	'The Hoax-Bots ',
	'Daryl, The Double-Dealing Gypsy ',
	'Wife Beaters ',
	'Advantage Wand ',
	'Leg-Up Posse ',
	'Burlesque Orchestra ',
	'Booty For President ',
	'Dinosaur Milk ',
	'Profit for Pandas ',
	'Peoples Republic of Beanstalk ',
	'Beanrock ',
	'BOSTON ROCK ',
	'Cell Phone Fantasy ',
	'Frozen Turkey Bowling ',
	'Polyester Party ',
	'Law Muffin ',
	'Idle Chat ',
	'187 ',
	'The Retarded Goats ',
	'I Ate Your Mom Out ',
	'Roses for Stalin ',
	'The Awesomes ',
	'The Brain Stem Culture Force ',
	'The Pap Smears ',
	'Best Of The Best ',
	'The Bumble B\'s ',
	'Stilletto Ghetto ',
	'Pinnochio\'s Wood ',
	'The Trout Sniffers ',
	'Bra Size 11 ',
	'HEARTFELT ',
	'The He-Men ',
	'The Concerned Citizens ',
	'Cute Anus ',
	'Beeswax and Candlesticks ',
	'Helicopter Giraffe ',
	'MP3s For All ',
	'Buddy Trouble ',
	'Metallic Objects ',
	'Red Foot Green ',
	'Masturbate ',
	'The Hopscotch Twins ',
	'Licorice Daddy ',
	'Earth Magnet ',
	'Big Black Knuckles ',
	'Easy Bake Trio ',
	'Barrel Full of Trout ',
	'The Gold at the End of the Rainbow ',
	'Big Black Knuckles & His Good Morning Friends ',
	'The Woburn Project ',
	'The Timeshares ',
	'The 6am Bikeride ',
	'Ghetto Diarrhea ',
	'German Facelift ',
	'5 Dollar Manslaughter ',
	'All You Need Is L.O.V.E ',
	'Leonard Ogden Virus Evasion ',
	'King Sphincter ',
	'Kermit the Fraud ',
	'Molar Mario: The Musical Odyssey ',
	'The Bicuspeds ',
	'License Plate Men ',
	'Cucumbers from Heaven ',
	'Pog Form ',
	'Yodel for Joy ',
	'Pimples & Zits ',
	'The Distributors ',
	'Stock Option 1 ',
	'Hold One Down For Hershey\'s ',
	'Doo-Doo Covered iPod ',
	'Say Your Alphabet Backwards ',
	'The O McDonalds ',
	'The Toe Tappin Tomboys ',
	'AOL Instant Messenger ',
	'Deceiving Looks ',
	'Winter\'s Second Glance ',
	'Croutching Liger ',
	'Bump Me To An A ',
	'Very Superstitious ',
	'Sisters Who Don\'t Slouch ',
	'For Pete\'s Sake ',
	'The Crooked Eye ',
	'Genius at Work ',
	'Razorblade & The Toxic Fumes! ',
	'Closed Captions ',
	'Pirates of the Carborator ',
	'Drop the Cabbage ',
	'The Cabbage Droppers ',
	'The Weak Spleen ',
	'Dumpstein ',
	'Rumble in the Bronx ',
	'Jungle & Tonic ',
	'Booker T Washington and the Freedom Slaves ',
	'Monseiur Godzilla & His Band Of Aboriginees ',
	'Mr. Big Shot & The Innappropriate Hand Gestures ',
	'Potential For Stardom ',
	'Suicide Switchblade ',
	'Simon Says Fuck ',
	'Besides That It\'s All Good ',
	'Damage Code Zero ',
	'Rhyme A Dozen ',
	'Skittles & Dunks ',
	'Jim Jones Kool Aid ',
	'Freddy Kruger Snake ',
	'The Shapeshifting Jabberwockies ',
	'The Nasal Pasage Submarine ',
	'Infinite Forever Team ',
	'Robbing Don Juan Collins ',
	'Personal Cymbal ',
	'Splash Gallant ',
	'Avalanche Monkeys ',
	'Mustache Brainwave ',
	'Flex For Your Brother ',
	'The New Girl ',
	'The Riverfront Nasty ',
	'Assistant Gargoyle ',
	'My Opiate Shake ',
	'Putty Business ',
	'Carnation Fire ',
	'Vomit Thompson: The Circumstance ',
	'Lunch Son ',
	'Time Daniels ',
	'Stuff Nugget ',
	'Bunt Rock ',
	'Monster Kitten ',
	'Triple Blunt Fantasy Ride ',
	'Red Meat Drugs & The Anemic Reason ',
	'Swan Balls ',
	'Flavin of the Glavin ',
	'Acid BeatBox Prophecy ',
	'ETC (Eat The Celery) ',
	'Igloo Factory ',
	'Artichoke Fellas ',
	'The Rocky Mountain Folks ',
	'Giraffe Ladders ',
	'The Latest Gods ',
	'Murda Street Sons ',
	'Front Porch ',
	'Cheshire Magnet ',
	'Sensei Sayonara ',
	'Booting In St. Louis ',
	'Third Shift Greenbots ',
	'Debbie Lightning ',
	'Delicious Mayhem ',
	'Hourly Effervescence ',
	'The Giddy HTML ',
	'Art Deco & The Return To Victory ',
	'Horrible Odor & The Scat Fight From Mars ',
	'The Drug Traffic Controllers ',
	'The Protein Priests ',
	'Hip-Hop Higgins ',
	'Fountain of Funk ',
	'Philly Blunt & The Cowboy Killers ',
	'The Booty Soldiers ',
	'Cause And The Effect ',
	'Operation Clandestine ',
	'Chinese Ambivalence ',
	'Architects of Sound ',
	'Pudding Cochran ',
	'Bunsen Burner and the Scientific Method ',
	'Fecal Matter & The Bowel Movements ',
	'Spidey Sense and the Tingling Sensations ',
	'Shadow Daps ',
	'Dangerous Riptide and the Absent-Minded Lifeguards ',
	'Figures Of Speech ',
	'Annie May and the Metaphor Phantoms ',
	'Hit Ten Mullets ',
	'The Apostles of Grayskull ',
	'The Parable of the Donkey ',
	'Psycho Elixir ',
	'Eliptical Genius ',
	'Conundrum Jackals ',
	'Crackhead Poets ',
	'Sizzling Light and the Full Eclipse ',
	'Millenium Thesaurus ',
	'A Dash of Gusto ',
	'The Spice Boys ',
	'Whiff of the Gods ',
	'The Long Wine List ',
	'The Philharmonic Rice Patties ',
	'Heinous Anus & The Dutch Oven ',
	'Jerico Gladly and the First Dimension ',
	'Orangutan Rappers ',
	'Primitive Beat and the Evolutionary Doubters ',
	'Half of the Half of the Half & The One-Eighths ',
	'Times New Romans and the Italic Print ',
	'No One Likes a Tattle Tale ',
	'The Tattle Tailors ',
	'Trump Cards Face Up ',
	'Ginger Snap Nukkas ',
	'Frankincense and Murda ',
	'Grumpy Droid & The Happenstance ',
	'The Turn-Ons ',
	'Men of Pause and the Hot Flashes ',
	'See Three Pee, OH! ',
	'Chinese Eyes ',
	'Cruella Deville and the Dog Pound ',
	'The Pork Of Pollution ',
	'The Republican Hit Squad ',
	'Alyre MacLure and the Silly Goons ',
	'Brad Cancer ',
	'Molecule ',
	'Reduce The Flame ',
	'Bruce Gay and All the Colours of the Rainbow ',
	'Andthe Allthe ',
	'Committment to Cactus ',
	'Pretty Good Peyote ',
	'The Dollar Hills ',
	'The First Time Ever ',
	'Oragami and the Little Paper Ducks ',
	'The Shoulder Blades ',
	'Algorithm & The Calculus Crew ',
	'Heat Moon and the Full Moon Band ',
	'Teddy Smooth Graham Crackas ',
	'How Do You Feel About Male Frontal Nudity ',
	'The Dome Catchers ',
	'Toxic Algea ',
	'Purpose Porpoise & The Dolphins Of Meaning ',
	'Dark Matter Dorm Life ',
	'Simple Minded Geniuses ',
	'The Big Idea ',
	'Heat Stroke and the Blazing Sun Spots ',
	'Who Does That?! ',
	'THE CAPS LOCKS ',
	'The Mini-Golf Dumps ',
	'Too Many Booby Traps ',
	'Ying Yang Triplets ',
	'Bone Chumps N\' Melody ',
	'Notorious BIB ',
	'Friend Of Fred ',
	'Crashing In My Calvin Kleins ',
	'Persian Aversion ',
	'Version 3.1.6 Mafia ',
	'Holiday Hooligans ',
	'Steady Rock Limbo Eaters ',
	'Safety In Plunders ',
	'The Switch Hitters ',
	'Northern Trophy ',
	'Norm Thompson\'s Awkward Moment ',
	'Hell Is Awkward ',
	'Silence of the Lips ',
	'Pajammers ',
	'Gatorade Matt & The Knowledge Cats ',
	'Vote Fantastic ',
	'An Apple A Day ',
	'3rd World Henchmen ',
	'The Headless Horesemen ',
	'Sgt. Red Dot & The Hindu Vibration ',
	'Conjoined at Birth & The Siamese Twins ',
	'Rumple Stilts Men ',
	'Too Sleepy To Drive ',
	'Bud Miller & The Hangover Kids ',
	'Smoking Crack & The Life Lessons ',
	'Vigilante Brown and the Shadows of Dubious Origin ',
	'The Soft Serve Gentlemen ',
	'Nauseas Presents ',
	'Subpoena Frankenstein and the Merchandise Celebrities ',
	'Siphon Danger from the Mouth of Fury ',
	'Pleasure Town ',
	'Distant Grandson and the Occasional Birthday Cards ',
	'Diamond Lou & The Designated Hitters ',
	'The Blaze Face Racers ',
	'The Megalomania Funk Factory ',
	'The Jaw-Droppers ',
	'EU-CA-LYP-TUS ',
	'Brush With Death ',
	'Tooth Decay Terrorists ',
	'Frozen Heart ',
	'Iron Mike and the Chain Gang Philosophers ',
	'Sentimental Squid ',
	'Porcupine Spine ',
	'Trolls Galore ',
	'Gnomes On Broadway ',
	'Rocket Shoes ',
	'Boots for Charles ',
	'Xavier Smiggles, the Rhinestone Diva ',
	'Black Fang and the Dynamo Septuplets ',
	'Thomas Jefferson & The Declarations Of Independence ',
	'TJ & The Decks Of Indy ',
	'Ducks in the Alley ',
	'Dings in the Acura ',
	'Dents in the Apple ',
	'Dentures in the Aperture ',
	'Donkeys in the Avalanche ',
	'Dingos in the Agency ',
	'Dipset in the Area ',
	'Deltron in the A drive ',
	'Disco in the Avenue ',
	'Deadbolts in the Apartment ',
	'Dildos in the Anus ',
	'DICKS IN THE ASS ',
	'The Alabama Dam Hammers ',
	'Haliburton Hurtin Duckets ',
	'Deals in the Astrodome ',
	'Dimples in the Asphalt ',
	'Dillemas in the Architecture ',
	'Dexterity in the American Way ',
	'Daniel Isn\'t Having It ',
	'Rogue Ogre ',
	'Amac Goes To Grad School ',
	'The Comma Seperated Values ',
	'The Hunger To Win ',
	'The Clever Farm ',
	'Top Rock Butterscotch ',
	'Your Mom Is Shady ',
	'The Testicular Dancers ',
	'Holiday Salad Bar ',
	'Affluent Menace ',
	'Street Car Named Destiny ',
	'Indian Hobo ',
	'Bridge to Canada ',
	'Vagabond Market ',
	'Empire State and the Skyscrapers ',
	'Film at Eleven ',
	'Rabbit Corps ',
	'United States of Blunts ',
	'Cold Fuzion Coordinates ',
	'Bowling For Engineers ',
	'Catatonic Mamba ',
	'Salsa for Seven ',
	'Cha Cha Mammas ',
	'Vicious Eyebrow & The Velvet Fleece ',
	'Table for Octo ',
	'The Neat ',
	'Seismic Sediment and the Tectonic Plates ',
	'Club o\' Seals ',
	'Volcano Pimps ',
	'Continental Shift and the Quakers ',
	'Brutal 80 ',
	'Hexagon Time ',
	'Serious 7 ',
	'Ghost ',
	'Random Math ',
	'In Case of Fire ',
	'Geo Boyz ',
	'Barrel of Monkeys ',
	'Slippery Sickness ',
	'Fifth Dimension Zorro ',
	'Flaccid Ministry ',
	'Ninja Goes To Camp ',
	'Enjoying A Word ',
	'A Fiend for You and Me ',
	'Helicopter Grapes ',
	'Coniferous Forest Crew and the Merit Badges ',
	'Act of God and the Hailstorm Dents ',
	'Shimmy & Shake ',
	'Give A Man A Fish ',
	'Endoplasmic Reticulators ',
	'Los Banditos and the Bullet Holes ',
	'Ricochet Williams and the Showdown at Dusk ',
	'Leave Now & The Stop Making Band Names ',
	'Crack Rock Stockton ',
	'The Post-Nasal Hip-Hop Parade ',
	'The Inconvenient Startle Rockets ',
	'Dudes of Girth ',
	'Ricoshit ',
	'Bongo Bruise ',
	'You\'re In Big Treble ',
	'First Bass ',
	'The Sons Of Sound ',
	'Live Slow ',
	'The Characters Of Velcro ',
	'The Litter of The Sticky Critter Hitters ',
	'Thump Duck ',
	'The Shifty Looks ',
	'Stool Pigeon & The Dodgy Slacks ',
	'Officer Slugs ',
	'Organic Bananas & The Expensive Produce ',
	'A Custom Dusting ',
	'The Knuckle Heads ',
	'Or Else ',
	'The New Band Names ',
	'Marty McFly and the Doc Brown Blues Band ',
	'Crisper Crisp and The Fridgedaires ',
	'Micro Wave and the Super High Frequencies ',
	'The Problems ',
	'Gadzundheit and the Sticky Phelgm ',
	'Nipple Tickle ',
	'Over The Cube Wall ',
	'Duck Crew ',
	'The Mollusk Crew ',
	'Ninja Ice Grill ',
	'Band Sans Wackness ',
	'Fish Tank Fetish ',
	'The Grassy Knollers ',
	'Crunk Nukka Sukka Juice ',
	'The Bogs ',
	'Pony Up The Doug ',
	'The Blunt Brothers ',
	'The Rigid Left Eye of Dr. Canada ',
	'The Unknown Invisible Force ',
	'Slut Elevator ',
	'Water Hose Clergy Science ',
	'Dick Diamond & The Bling Blingas ',
	'The Mammary Appendages ',
	'Pastarific ',
	'Super-B and the RingTones ',
	'Vern and the One-Liners ',
	'MegaPhone Mike and the Volcano Crust ',
	'The Crush-Stations ',
	'Good ol Dandilions ',
	'Boombox Brothers ',
	'Four Score and Seven Year Bandits ',
	'Little Bo Peep and the Stungun Posse ',
	'Jackie Treehorn and the Unpaid Debt ',
	'The Year Of The Gat ',
	'Salad Sans Spinach ',
	'E. Coli Bastards & Such ',
	'Tremor Nose Wrinkle Task Force ',
	'Diabetes Fist ',
	'Grundle Gremlins ',
	'Sick Flippin Taxi ',
	'Mantle For Santa ',
	'Agressor Mayhem ',
	'Pink Terror and The Palm Tree Shadows ',
	'Slime Talk ',
	'Black Mussolini ',
	'Your Mom Googles ',
	'Nullified Nukkas ',
	'Genderless Giants ',
	'Chlorophilly ', 
	'Juice Katana ',
	'Broccoli Tonight ',
	'Ramirez Banana ',
	'Half-Eaten Danish ',
	'Raja Smurf ',
	'Eagle Pose Posse ',
	'Satan Cabbage ',
	'Emergency Tomato ',
	'Cobra Balloon ',
	'Delete That Word ',
	'Excuse The Freshness ',
	'Chinese Elevator Compromise ',
	'Tea Time For Betsy ',
	'Football & The Zombie Tailgate ',
	'Table For Twenty ',
	'Roll AIDS ',
	'Afternoon Clover Haven ',
	'Bandwidth Reynolds ',
	'Vulture Grease ',
	'Jamaica Troll ',
	'The 9 Dozen ',
	'Fruit Stacks ',
	'Olive Henry ',
	'Mustang Bishop ',
	'The Kayak Guys ',
	'The Gaa Gaa Dolls ',
	'Tickle Me Hell No ',
	'The Mason-Dixon Dudes ',
	'The Cacti Crew ',
	'Two Exits Til Chicago ',
	'Fell Down The Stairs ',
	'Loser Disposal ',
	'Lords Of The Exit Door ',
	'L.A. Cool ',
	'Celebate Dinosaur ',
	'Tinkle Brothas ',
	'Missile Christmas ',
	'German Three ',
	'Texas Heat & T ',
	'The Crazy Digits ',
	'Nut Bussas ',
	'The Arabian Goggle Trio ',
	'The Highly Effective People ',
	'The Jerks & The People Who Hate Them ',
	'Recovering Ankle Biters ',
	'Sloppy Top Juggle Squad ',
	'Wine And Pancakes ',
	'Scary Bulge & The Mixed Batter ',
	'Mrs. Jugular & The Cocktail Mishaps ',
	'Coney Island Broncos ',
	'Glass Laundry ',
	'Hey, Pancreas! ',
	'Monkey Jump ',
	'Veggie Club ',
	'Salmon Iller ',
	'Crystal Clear Cutlery ',
	'Doberman Dingo ',
	'Gravity & The Laws of Fizzix ',
	'Rocks In The Scotch ',
	'Panters In The Pocket ',
	'The Pumpkin Sisters ',
	'Australian Hot Spot ',
	'Great Wall of Weirdo Nukkaback ',
	'Impressive Talk ',
	'Retro Flow & The Bad Excuses ',
	'Magic Sticky Hands ',
	'Instantaneous Osprey & The Chicken-Flavored Crystals ',
	'Solar Cow ',
	'Hardboiled Nukkas ',
	'Manure Harp ',
	'Flaming Fetus ',
	'Definitely Dan ',
	'The Penguin Sisters ',
	'Brake For Llamas ',
	'The Bob Ross Fixins ',
	'Made In Sri Lanka ',
	'You Can\'t Recycle Toothpaste ',
	'Boba Shuttle ',
	'Switch Back To 2% ',
	'Gallop Factory ',
	'Nickel Clickin Tickle Ticket ',
	'Easy Now & The Sideways Glance ',
	'Silent Earl & The Chatty Cathy\'s ',
	'China Forced you to Quit ',
	'Nullified Nillas ',
 	'Beer Suckling Pigs ',
	'Jesus Wears Tights ',
	'God Sings Karaoke ',
	'Tiger Balm Juiceball ',
	'Celestial Cowbell ',
	'Landfill Surfing ',
	'Jerking Off With The Stars ',
	'Tom goes to Timeout ',
	'Birdie Magoo and the Tremulous Teetotalers ',
	'The Cow Wants a Candy Bar ',
	'Ferrets on LSD ',
	'Federal Agents Drive Like Patty Duke ',
	'Absinthe Orgasm ',
	'Female Panda Office ',
	'Greedy Bitches ',
	'The Hos Ate the Oreos ',
	'Who\'s Baking Ziti? ',
	'Buy Asia a Cigarette ',
	'Electrical Bananas ',
	'Organic Styrofoam ',
	'Hepatitans ',
	'The Polish Muslim Democrats ',
	'Presidential Tennis Courts ',
	'Freud and the Ego Maniacs ',
	'Homo Erectus ',
	'Black Michael Jackson ',
	'Elbow Grease and The Helping Hands ',
	'Lefty McRight ',
	'The Little Baby Fingers ',
	'Polish Sausage Fingers ',
	'Necromaniacs ',
	'Lumping Jesus Lizards ',
	'The Blinding Lights ',
	'Proper Doctor Attention ',
	'The Dilating Orifices ',
	'CD\'s Nutz ',
	'Phony Jewish Clown and the Gemini Capricorns ',
	'Turn Down the Suck ',
	'Lethal Buddhas ',
	'Ease Up On the Horseraddish ',
	'Insert 3 Fingers ',
	'Tied at 4 ',
	'Gold Medal Russians ',
	'The Czech Box ',
	'Twister with Stretch Armstrong ',
	'Twister Starring Your Mom ',
	'Pee in the Closet ',
	'Go Go Gadget Bitches! ',
	'Knife-Wielding Ghosts ',
	'Mashed Potato Molesters ',
	'Pre-Madonna Gangstas ',
	'Mr. Potatoe Legs ',
	'AC and the C-rings ',
	'Dap Ninjas ',
	'Beer in your Cornflakes ',
	'Rock Lobsters ',
	'Teaspoon Full of Octopuss ',
	'The Frozen Kidney ',
	'Flying Killer Horses ',
	'I Don\'t Care Too Much for Reggae ',
	'Sensational Robot Brothers ',
	'The Flying Mesopotamians ',
	'The Hardy Boys and their Stupid Highwater Pants ',
	'Pimp Your Balls ',
	'Topsoil Worms and the Invisible Nancy ',
	'Fortune 501 ',
	'There\'s a Flipside to That ',
	'Tied to the Bedpost ',
 	'Tornado Ruffians ',
	'Speaks in Tongues ',
	'Who\'s This Guy? ',
	'If Your Mother Only Blew ',
	'Upside Your Head ',
	'49 Reasons to Kill Yourself ',
	'Charlie and the Rocklate Factory ',
	'Buying Crack on the Corner ',
	'I\'m Glad We\'re Not French ',
	'Tired of The Milk Shake ',
	'Living Dangerously ',
	'Sumo Wrestlers with Butterfly Wings ',
	'I\'m Going To Need A Bigger Boat ',
	'Speaking Without Tongues ',
	'I Told You Not to Push That Button ',
	'Sex on the Boss\'s Desk ',
	'Computer Generated Reason ',
	'The Dr. Spock Trio ',
	'Illegal Noise Police ',
	'Fist Full of Funk ',
	'Magnet-Beak Seagulls ',
	'Mechanical Bull Riders ',
	'Mercedes Dollars ',
	'Rodriguez and the Moustache Boys ',
	'Baby Modulator ',
	'Silly Rabbit ',
	'Third-Floor Dragon Sex ',
	'Hotter than Alaska ',
	'The Five Star Generals ',
	'Cauliflower Mind ',
	'The Sick Sense ',
	'Roller Derby Cowboys ',
	'Terror Apache ',
	'Chalupa Music ',
	'Dead or Alive ',
	'Johnny Apocalypse & The Luddites ',
	'Sigmund Squadron (Siggy Squad) ',
	'Red Tongue and the Popsicle Pushers ',
	'Who Is Rick? ',
	'Empty Pocket Riders ',
	'Get Out of The Pool! ',
	'Swimming with Sharks ',
	'The Televisions ',
	'Urinary Tract Infection & The Lack Of Cranberry Juice ',
	'A Pound of Sound ',
	'Teach God The Alphabet ',
	'Ransom Note and the Deliberators ',
	'Makes Sense to Pedro ',
	'The Easy Bake Ovens ',
	'Explosive Miranda ',
	'Deep Rumble ',
	'The Face Lifters ',
	'Hella Flounder ',
	'The Bull-Riding MC\'s ',
	'Don\'t Ask Me ',
	'Fruit in My Soup ',
	'The Bangs ',
	'The Grammar Slammers ',
	'The Techno Drome ',
	'Paper Plate & The Dirty Dishes ',
	'This Is The Deal ',
	'Sideburn Symphony ',
	'Amazon Tiger Fist ',
	'Kid Kangaroo and the Joy Jumpers ',
	'Packing Machismo ',
	'Power Everything ',
	'Tim Allen and the Socket Wrenches ',
	'Patrick Ewing at the Door ',
	'Fresh Out Of Fun ',
	'Mad Bluntski ',
	'Cousin Of Death ',
	'Sunbathe With The Dead ',
	'Pluto Rolls Gorilla Thumbs ',
	'Island Logic ',
	'Trumping Geographical Tactics ',
	'Geo-Graphix ',
	'Lactose Tolerant ',
	'The Lactose Tolerators ',
	'The Vibrating Seat Cushions ',
	'5 Metres of Snow ',
	'The 5 Meter Blunt ',
	'Gorilla Thumb ',
	'Adam C Fresh & The Monsters Of Religion ',
	'Artificial Cat Soup ',
	'Monster of the Fridge ',
	'The Refridgerators ',
	'Incessant Motor Noise ',
	'Tick Taco Toe ',
	'Upsidedown Grandmother ',
	'Suitable Rhino ',
	'Sonic the Hedgefund ',
	'Thor and the Lightning Bolts ',
	'Inverted Monk ',
	'Frizbee Dog ',
	'Purple Sunday ',
	'Eskimo Fashion Cats ',
	'Three Long Days in the Forest ',
	'Paper Plate and the Plastic Utensils ',
	'Spoon to the Eye ',
	'Beaver Skinning and the Strange Merit Badges ',
	'Boy Scouts Makin Power Moves ',
	'Freedom Fighting Wavelengths ',
	'Stereo Hi-Jinx ',
	'The Fabulous Eagle Brothers ',
	'Neutral Color Scheme ',
	'Disaster Dead Ahead ',
	'Kissing Cousins ',
	'Give a Man a Funky Fish ',
	'Sayonara Sweatpants ',
	'Staples for Suzie ',
	'The Heart Transplants ',
	'Paper, Plastic, or Perforated Metal ',
	'Abominable Phlegm Daddies ',
	'Instant Root Beer ',
	'Gay Ghost ',
	'Dont Mess with T-Rex ',
	'Feathered Together ',
	'Helicopter Ride and the Worst Blind Date Ever ',
	'Make Mine a Glass of Clorox ',
	'Who Needs a Chaser? ',
	'Tee Time at NEVER ',
	'Chilly Hoola Hoops ',
	'The Rectum Motion Sensors ',
	'Dont Step on the BOOM! ',
	'Apocalypse Sensor ',
	'Uterus Detectives ',
	'University of Terror ',
	'Mammary Overdrive ',
	'Lottery Tickets with No 7\'s or 8\'s ',
	'Where is The Church? ',
	'Don\'t Call Me God ',
	'Okay, You Can Call Me God ',
	'Civilians in Trouble ',
	'Godzilla\'s Vagina ',
	'Macho Man Randy Savage is Married To Vanessa Williams ',
	'Two Rabbits are Better Than One . . .Muskrat ',
	'Tidal Wave of Bees ',
	'Woozy Pop Judo Chop ',
	'Reasonless Muffins From God ',
	'A Meaningful Roundabout ',
	'Scratching and Bitching ',
	'Old Fashioned Flatulence ',
	'Fuckasaurus Sex ',
	'Daily O-Ring ',
	'Bizarre Burial Rights ',
	'Selling Kids ',
	'Backyard Cemetary ',
	'The Dicked-Her Scale ',
	'Kill Her with Kind Nuts ',
	'King of the Ashtray ',
	'Rolling On The Floor Vomiting ',
	'Stomach Full of Bling ',
	'The Data Transfer Jesus ',
	'The Dead Sea of Kidney Stones ',
	'Comma Separated Meth ',
	'Bulldog Knows Why ',
	'Warlock Paul and The Department Of Justice ',
	'Thanks for the Fun! ',
	'Nazi Pie ',
	'Slimey Ruckus Heads ',
	'The Paramecium Hyperbole Death Rock Symphony Project ',
	'The Devastating Napkin Developments ',
	'50-Years Old And Furious ',
	'Deaf, Dumb, & Fresh ',
	'Muck Nukkas ',
	'Gerbil Fantasy ',
	'Techmo Super Bowls ',
	'Nilla Wafers ',
	'Fried Chick ',
	'Ten Chukkas ',
	'Dead Beat ',
	'Final Fantasy Wiggas ',
	'Figure it Out or Die ',
	'Nifty Shifty ',
	'Go for Your Gun ',
	'Teddy Smooth Smokes Mad Blunts ',
	'Ted Says So ',
	'Baffle Iron ',
	'Walnuts for Justice ',
	'Jesus Loves Pomegranate ',
	'My Foot is Asleep ',
	'The HellaCopters ',
	'Amorphous Liquids Team ',
	'Who Is That ',
	'Tennesee Gorilla ',
	'Dusty and the Swifter Sweepers ',
	'Two Gallons of Funk ',
	'The Sonnnnns ',
	'Tigers on the Moonshine ',
	'Dick Force 5 ',
	'The New Hampshire Nile ',
	'Whale Meat and the Penguins ',
	'Don\'t Laugh ',
	'Dale Has a Mangina ',
	'Five Equals Six ',
	'New Kids on the Dock ',
	'Iffy McSniffy ',
	'Dolphin Envy ',
	'Loaded Squirt Gun and the Itchy Trigger Fingers ',
	'Federal Express ',
	'Domino Dynasty ',
	'Dictionary of Doom ',
	'Hexagon and the Odd Shapes ',
	'Infinity and Beyond ',
	'Triforce ',
	'Super-Educated ',
	'Smarter Than Spock ',
	'Lil Miss Goody 3 Shoes ',
	'Halfway Around the Globe and Back ',
	'Neva Eva ',
	'Chinese Pets For Dinner ',
	'My White Socks ',
	'Stop Using the N word in Band Names ',
	'Wiggapedia ',
	'Brain Surgery for Dummies ',
	'Your Face ',
	'Don\'t Eat That ',
	'Steve is Back ',
	'The Devil Wears FUBU ',
	'Tatas are Great ',
	'Danny A and the Double Helix ',
	'Dinosaurus ',
	'Fifth Ave Donkey ',
	'Skinny White Kid and the Fast Metabolism ',
	'Faster than Hell ',
	'Stereo for Elvis ',
	'Time to Light ',
	'This Bowl ',
	'Wicked Smot ',
	'Negative 3 ',
	'Hurricane Dick ',
	'Gizmo is Gonzo ',
	'Nine to Nil ',
	'Ipswitch can Switch Hit Bitch ',
	'Dig Deep ',
	'Behind Curtain Number 3 ',
	'Earth Fire Wind Water Blunts ',
	'Teach a Man to Fish then Smoke a Blunt ',
	'It\'s Nine Thirty Dood ',
	'Even God Gets Bored ',
	'Retarded Elf ',
	'Igloo Mansion ',
	'Tennis Is Only Fun When You\'re Drunk ',
	'Fuck Nancy ',
	'French Ticklers ',
	'What is a French Tickler ',
	'Ancient Website ',
	'Checkers of Fury ',
	'Mink Bomb ',
	'TV Turkey & The Eight Bassists ',
        'Osirus Footwork ',
        'Million Bajillion ',
        'Nifty Sniffers ',
        'Puppy Pants ',
        'TV Turkey and the Nine Bassists ',
        'The Gropers ',
        'Hate to Break it to You Like This ',
        'The Insignificant Others ',
        'Left Field is for Redheads and Sausage Monsters ',
        'Try Not to Fall Out of Bed Again ',
        'Septic Mermaid ',
        'With Jim Beam Anything is Possible ',
        'The Touchers ',
        'Will Smith of Funk ',
        'German Giraffes Don\'t Actually Speak German ',
        'Bong Rips and the Infinite Binoculars ',
        'Metal Skeleton Detectors ',
        'Average Sized Ape ',
        'Glands of Steel ',
        'Swollen Triceretops ',
        'Evil is my Middle Initial ',
        'Honk if you Love Excruciating Pain ',
        'Space Clouds ',
        'Eagle Eyed Pidgeon ',
        'Useful Juice ',
	'Space Rash ',
	'Scandanavian Edits ',
	'Rick The Hard Drive ',
	'Backrub Thompson ',
	'Proliferate Life Insurance ',
	'The Sample Size '
);


function GetBandname(outputtype)
{
	if(++Number > Bandnames.length - 1) Number = 0;
	if (outputtype==0)
		document.write(Bandnames[Number])
	else if (document.getElementById)
		document.getElementById("boston").innerHTML=Bandnames[Number];
}

var Number = Math.floor(Math.random()*(Bandnames.length));






